name: publish
on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  build-and-publish-nuget:
    name: build and publish nuget
    runs-on: windows-2025-vs2026
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # get full History to make sure tags are included an thus git-describe works

      - name: Get version number
        id: version
        uses: PaulHatch/semantic-version@v6.0.2

      - name: Generate semver version number
        id: generate-version
        shell: powershell
        run: |
          if("${{ steps.version.outputs.is_tagged }}" -eq "false")
          {
            $semver_version = "${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }}-beta.${{ steps.version.outputs.increment }}"
          }
          else
          {
            $semver_version = "${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }}"
          }

          $assembly_version = "${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }}.${{ steps.version.outputs.increment }}"

          echo assembly-version=${assembly_version} >> $env:GITHUB_OUTPUT
          echo semantic-version=${semver_version} >> $env:GITHUB_OUTPUT

      - uses: nuget/setup-nuget@v4
        with:
          nuget-api-key: ${{ secrets.GITHUB_TOKEN }}
          nuget-version: "6.x"

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v5
        with:
          source-url: https://nuget.pkg.github.com/renewedvision/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}  

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v3

      - name: Build
        id: build
        shell: powershell
        run: |
          msbuild src/RenewedVision.Wpf.Interop.DirectX.slnx -restore -p:RestorePackagesConfig=true -p:Version="${{ steps.generate-version.outputs.semantic-version }}" -p:AssemblyVersion="${{ steps.generate-version.outputs.assembly-version }}" -t:Rebuild -p:Configuration=Release -p:Platform=Win32
          msbuild src/RenewedVision.Wpf.Interop.DirectX.slnx -p:RestorePackagesConfig=true -p:Version="${{ steps.generate-version.outputs.semantic-version }}" -p:AssemblyVersion="${{ steps.generate-version.outputs.assembly-version }}" -t:Build -p:Configuration=Release -p:Platform=x64

      - name: Package
        id: package
        run: |
          nuget pack ./RenewedVision.Wpf.Interop.DirectX.nuspec -Version ${{ steps.generate-version.outputs.semantic-version }} -Properties "NuGetBinariesWin32=src\Win32\Release;NuGetBinariesX64=src\x64\Release"

      - name: Publish Nuget to GitHub registry
        shell: powershell
        run: |
          foreach($file in (Get-ChildItem . -Recurse -Include *.nupkg)) {
            dotnet nuget push $file --skip-duplicate
          }
